# name: Keep Backend Alive

# on:
#   schedule:
#     - cron: "*/10 * * * *"   # every 10 mins
#   workflow_dispatch:

# jobs:
#   ping:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Call alive endpoint
#         run: |
#           curl -f --max-time 20 \
#                -H "Api-Key: ${{ secrets.DEBUG_API_KEY }}" \
#                https://argueseyeapi.onrender.com/management/internal/alive
